.TH lis 1 "May 2016" "version 0.1"

.SH NAME
lis \- Daemon for controlling backlight brightness.

.SH SYNOPSIS
.B lis [OPTION]...

.SH DESCRIPTION
Auto dim/undim backlight when a user is idling/active.

.SH OPTIONS
.TP
.B -c
path to config file. Default is
.I /etc/lis.conf.
.TP
.B -h, --help
display help and exit.

.SH AUTHOR
Written by Mikkel Oscar Lyderik.

.SH SEE ALSO
.BR lisc (1),
.BR lis.conf (5)
